# Site Settings
baseurl: 		""
title: 			Bruce's Blog

name: 			Bruce's Blog
description: 	A beautifully contemporary and elegant Jekyll theme
url: 			"https://brucegx.github.io/"

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		indiqo
email: 			hello@indiqo.eu

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2014 Indiqo.	

# Build Settings
permalinks: 	pretty

plugins: [Jekyll-paginate]